language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
    - functions/node_modules
    - gui/node_modules
install:
  - yarn --frozen-lockfile
  - (cd functions && yarn --frozen-lockfile)
  - (cd gui && yarn --frozen-lockfile)
after_success:
  - ./travis-deploy.sh
