name: build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn --frozen-lockfile
    - run: cd gui && yarn --frozen-lockfile && yarn build
    - run: cd functions && yarn --frozen-lockfile && yarn build
