name: build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: build gui
      run: yarn --frozen-lockfile && yarn build
    - name: build functions
      run: cd functions && yarn --frozen-lockfile && yarn build
    - name: deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
